# Generated by Django 5.0.2 on 2024-02-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiproblem',
            old_name='internship',
            new_name='internshipid',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='organization',
            new_name='organizationid',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('internshipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('internshipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.internship')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
    ]
