# Generated by Django 5.0.2 on 2024-02-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency_score', models.IntegerField()),
                ('proficiency_level', models.CharField(max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.skill')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user'),
        ),
    ]
